language: go
go:
  - 1.5
  - 1.6
  - tip

env:
  global:
    - GO15VENDOREXPERIMENT=1

install:
  - make get-devtools
  - export PATH=$PATH:$HOME/gopath/bin

# TODO: see https://onsi.github.io/ginkgo/#ginkgo-and-continuous-integration
# Maybe separate `make ci` tasks that does random order, coverage, etc.
script:
  - make lint errcheck coverage

after_success:
  - |
    bash <(curl -s https://codecov.io/bash) -f connect.coverprofile || \
        echo "Codecov did not collect coverage reports"

# Container-based infra for builds that start faster.
sudo: false
